# Generated by Django 4.1.7 on 2023-03-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_user',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일자'),
        ),
    ]
