# Generated by Django 4.1.7 on 2023-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_user', '0002_alter_sp_user_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_user',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
